### ISSUE TITLE
shipper args needed for api interaction

### ISSUE THREAD

**Issue by ghost** [o2r-project/o2r-shipper#1]
Let's determine which arguments are needed to interact with o2r api and zenodo api:

_updated_
from o2r-api

- `-ercid` (used to retrieve erc filepath for bitstream, owner, metadata file in erc)
- `-recipient`: (e.g. "zenodo" or complete endpoint)
- `-userid` 'caller'

zenodo

- `-endpoint` (only needed if not connected to `recipient`. api base url, sandbox or non-sandbox)
- `-deposition_id` (only for update of existing depot)
- `-metadata` (only for update)
- `-access_token` (platform user or orcid user)

Any suggestions?

**Comment by nuest** [comment]
the shipper actually is "triggered" by the o2r api, so the two arguments above could be treated as "input arguments", things that must be provided by the caller. For the record, the caller id (user orcid) should also be required as an input.

**Comment by ghost** [comment]
will be redone in next commit.

**Comment by nuest** [comment]
Actually, the user ID is not required, since we should derive that from the provided authentication cookie.

**Comment by ghost** [comment]
yes, this is not the current design. documentation will come with next commit's readme.
