### ISSUE TITLE
Re-consider content of shipment's description

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-shipper#12]
When shipping to Zenodo, is it really useful to have the _publication abstract_ in the description, or should that now be instructions on how to work with the ERC?

Should there be both?

**Comment by ghost** [comment]
Zenodo dev docs describe the _description_ as:
> Abstract or description for deposition

But I hestitate to add technical instructions to the original abstract.

**Comment by nuest** [comment]
OK, no technical details. But there should at least be a sentence stating that the deposited item is an ERC, right?

**Comment by ghost** [comment]
No, I think that is not the right place, because librarians will use the description field for "What the authors say the work is about".

**Comment by nuest** [comment]
Ok.
