### ISSUE TITLE
Updated License Object

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-shipper#14]
Just to **inform** you: In the future, licenses will be described in the metadata as follows:
```JSON
"metadata":{
    "o2r": {
        "license": {
            "text": <String>,
            "code": <String>,
            "data": <String>,
            "uibindings": <String>
        }
    }
}
```
If this affects your code, be informed that it needs to be updated.

**Comment by ghost** [comment]
Yes this was my suggestion, but we haven't discussed this as a group. We should do.
Also please point out where this affects the shipper code. I think since your example is o2r metadata rather than e.g. zenodo metadata, the shipper will take brokered MD, so it doesnt see this anyway, right?

**Comment by nuest** [comment]
Right, shipper does probably not have to care about this. IMHO can be closed.

**Comment by jansule** [comment]
@7048730 As far as I understand, the `MASTER_MD_DICT` contains all metadata and will then be mapped to the required structure for each purpose (zenodo, o2r, etc.), right? Therefore, the mapping of the license object needs to be updated, so that it will fit again to the required structure of zenodo.

But @nuest is right in the point that shipper does not have to care about it, but rather o2r-meta.

**Comment by ghost** [comment]
Okay good, then I'm closing this
