### ISSUE TITLE
Update user level

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-shipper#15]
We now have a single list of user level information across all microservices:

http://o2r.info/o2r-web-api/user/#user-levels

@7048730 Should we stick with shipping only for `200` and above, or should we not allow it already at `100` for known users?

**Comment by ghost** [comment]
Just set known users to 200 as before and nothing needs to be changed I guess :)

**Comment by nuest** [comment]
Ok. I can make the PR.

**Comment by ghost** [comment]
No listen, what I meant is, why changing the 200 level anyway? We have range from 0 to 500. Does not matter if we put entitled user at "200" (as it was in the past) instead of "100" as documentated recently.
