### ISSUE TITLE
Remove Dockerfile.local

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-shipper#25]
The file `Dockerfile.local` for copying sources into the container to be build is not useful (anymore? never was?). Instead, `Dockerfile` should use `COPY` and not clone the repo, because the repo clone is what just happened on Docker Hub (where the image is build).

@7048730 If you have no objections, I'll prepare a PR. This should not affect anything you're working on.

**Comment by ghost** [comment]
sounds reasonable, please proceed

**Comment by nuest** [comment]
Sorry, my bad :man_facepalming:  Already included in https://github.com/o2r-project/o2r-shipper/commit/958499f2fceb424a4c441563078cc89a17f49876 in the `dev-repo_classes` branch.

**Comment by ghost** [comment]
yes, its not yet merged. Sry, didn't check before replying.
