### ISSUE TITLE
Download of zip stream via post

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-shipper#36]
If I want to download an ERC I make a POST request and as an answer I get a zip stream returned. This is conformant with the documentation. However, the client cannot handle zip streams when they are returned from a POST request. 

Therefore, it would be helpful to only return the url to a zip stream, when making the POST request. Then, when making a GET request to this url, the zip stream will be downloadable.

**Comment by jansule** [comment]
I have found a workaround for the problem. Therefore I will close this issue.

**Comment by nuest** [comment]
What is the workaround?? @jansule

**Comment by ghost** [comment]
@nuest you can predict the dl url if you know the shipment id

**Comment by nuest** [comment]
I am pretty sure that was not the workaround used. @jansule Does constructing the URL client side make things easier?

@7048730 Would you add a comment on construction of the URL to the API docs?

**Comment by ghost** [comment]
I mean the suggestion @jansule makes is quite reasonable: only give the zip stream as response to a get request. its cleaner but comes at the price of having two steps instead of one.

**Comment by jansule** [comment]
The workaround was to set the `response-type` of the request to `arraybuffer` and then create a blob object. Afterwards I attach a temporary url for this object to an dynamically added anchor. Then, I trigger a click event to download the zip. Solution for this found [here](http://jaliyaudagedara.blogspot.de/2016/05/angularjs-download-files-by-sending.html).

The steps might be more or less the same if we change the download to a GET request, but I would say that conceptually it makes more sense to have a GET request getting the zip-stream.

**Comment by ghost** [comment]
Okay, good to hear it works. I didn't expect angularjs to need that many steps for such a simple thing.
I tag this as enhancement, in case anyone wants to continue here in the future...
