### ISSUE TITLE
Shipment metadata show internal filepath

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-shipper#37]
When retrieving shipment metadata the response contains an internal filepath `dl_filepath`. This should not be send to the client. Example response of `api/v1/shipment/<shipmentId>`:
```json
{
"id": "422e1add-881f-4aa7-a846-6227cbb1d3c8",
"compendium_id": "wOgjB",
"deposition_id": null,
"deposition_url": null,
"update_packaging": null,
"recipient": "download",
"last_modified": "2018-01-09 15:33:08.867273",
"user": "0000-0001-8842-8658",
"status": "shipped",
"md": { },
"dl_filepath": "/tmp/o2r/compendium/wOgjB"
}
```

**Comment by ghost** [comment]
totally correct. do we need the dl_filepath information at all? apart from that, I can only reproduce this with docker

**Comment by nuest** [comment]
The filepath should not be exposed and I don't see where it would be needed.

**Comment by ghost** [comment]
me neither, I'm pretty sure it has come through only accidentally from here:
https://github.com/o2r-project/o2r-shipper/blob/c4b2d27750492bb484beb8d4722716ab98533518/shipper.py#L353
