### ISSUE TITLE
No title when creating shipment for zenodo sandbox

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-shipper#38]
When creating a shipment for zenodo sandbox many times the draft is titled `Untitled` even though a title exists (in all `metadata subobjects`).

**tested with metatainer**

Here a screenshot of the result in zenodo sandbox:
![image](https://user-images.githubusercontent.com/12186477/34769281-a65ab65c-f5fd-11e7-90dd-5385e194bd6a.png)

See an example of the metadata here:
```json
"o2r": {
           ...
           "title": "asdf2"
},
"zenodo": {
            "metadata": {
                ...
                "description": "asdf",
                "keywords": [],
                "license": {
                    "code": "MIT",
                    "data": "CC0-1.0",
                    "md": null,
                    "text": "CC0-1.0",
                    "uibindings": "MIT"
                },
                "title": "asdf2",
                "upload_type": "publication"
            }
        },
        "zenodo_sandbox": {
            "metadata": {
               ...
                "description": "asdf",
                "keywords": [],
                "license": {
                    "code": "MIT",
                    "data": "CC0-1.0",
                    "md": null,
                    "text": "CC0-1.0",
                    "uibindings": "MIT"
                },
                "title": "asdf2",
                "upload_type": "publication"
            }
        }
```

**Comment by ghost** [comment]
I doubt this is a shipper issue because the shipper does not know what's in the metadata. it just takes the whole object, e.g. `zenodo_sandbox` and pastes it to the repository request. does the transmission fail?
Since `title` is still the correct element name (verified from developer guide of zenodo because they lack a schema) and since this element title is in the metadata in the database, it is not either a problem of brokering. Hence this seems to be a zenodo issue.

**Comment by ghost** [comment]
could you try to edit the `license` manually to `cc-by` and try shipping again?
I'm not sure which phase in the creation process your metadata example is, but the license object in that json is too complex for zenodo. they support only one license.

**Comment by jansule** [comment]
I tried it also with only `cc-by` as license but this does not work as well.

**Comment by ghost** [comment]
Well, I could not reproduce your problem, title works just fine:
![image](https://user-images.githubusercontent.com/12831248/34773113-cd2b22a0-f60a-11e7-817b-bb3207070e90.png)


_edit:_ here is my db entry:

```
{
    "_id" : ObjectId("691417dd04b5d817d04ec77d"),
    "id" : "4XgD9",
    "candidate" : false,
    "metadata" : {
        "zenodo_sandbox" : {
            "metadata" : {
                "creators" : [ 
                    {
                        "name" : "Tester, Ted",
                        "affiliation" : "Univ"
                    }
                ],
                "publication_date" : "2017-02-05",
                "description" : "Some words about it.",
                "title" : "Just a test title",
                "upload_type" : "publication",
                "publication_type" : "other",
                "access_right" : "open",
                "license" : "cc-by",
                "communities" : [ 
                    {
                        "identifier" : "o2r"
                    }
                ]
            }
        }
    }
}
```

**Comment by ghost** [comment]
we discussed this and found it most likely to be connected with the md in the db. after cleaning it out, it worked. some elements need to be handled differently in the future, cf.
https://github.com/o2r-project/o2r-meta/issues/82

**Comment by jansule** [comment]
fyi it seems to work with the current license object as well. it seems just to be important to have a title and publication_date.

**Comment by ghost** [comment]
okay, good to hear. yes, I updated this in meta
