### ISSUE TITLE
Add option to include Docker binaries in shipment

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-shipper#5]
To make an ERC that is shipped to an archive more sustainable, we could add the current (=used) Docker version into the shipment. Installers for Linux, OSX and Windows add about 300 MB, Docker source code repo is 160 MB currently.

Questions:

- Where put these files? Should be in a files structure next to/outside the ERC imho.

**Comment by edzer** [comment]
And maybe an environment to run these installers in, e.g. a Docker image? I mean: where to stop?

**Comment by nuest** [comment]
Exactly there: with Docker. If we choose that as our abstraction layer, that's it.

But I see that the preservation of Docker might be better left to the maintainer of a reproducibility platform which uses ERC.
